// <auto-generated />
using System;
using BragadoTripConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BragadoTripConnect.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811051532_SeedOperatorsAndRoutes")]
    partial class SeedOperatorsAndRoutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BragadoTripConnect.Api.Data.Booking", b =>
                {
                    b.Property<string>("ScheduleRouteOrigin")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleRouteDestination")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ScheduleTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ScheduleCompanyCuit")
                        .HasColumnType("text");

                    b.Property<string>("UserDni")
                        .HasColumnType("text");

                    b.HasKey("ScheduleRouteOrigin", "ScheduleRouteDestination", "ScheduleDate", "ScheduleTime", "ScheduleCompanyCuit", "UserDni");

                    b.HasIndex("UserDni");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.Company", b =>
                {
                    b.Property<string>("Cuit")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cuit");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Cuit = "30-00000001-7",
                            Name = "21900"
                        },
                        new
                        {
                            Cuit = "30-00000002-5",
                            Name = "Santorini Turismo"
                        },
                        new
                        {
                            Cuit = "30-00000003-3",
                            Name = "Chevallier"
                        },
                        new
                        {
                            Cuit = "30-00000004-1",
                            Name = "Trenes Argentinos"
                        });
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HealthChecks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "ok"
                        });
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.Route", b =>
                {
                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.HasKey("Origin", "Destination");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Origin = "Bragado",
                            Destination = "Retiro"
                        },
                        new
                        {
                            Origin = "Retiro",
                            Destination = "Bragado"
                        },
                        new
                        {
                            Origin = "Bragado",
                            Destination = "Once"
                        },
                        new
                        {
                            Origin = "Once",
                            Destination = "Bragado"
                        });
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.Schedule", b =>
                {
                    b.Property<string>("RouteOrigin")
                        .HasColumnType("text");

                    b.Property<string>("RouteDestination")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("CompanyCuit")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("RouteOrigin", "RouteDestination", "Date", "Time", "CompanyCuit");

                    b.HasIndex("CompanyCuit");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.User", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.HasKey("Dni");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.Booking", b =>
                {
                    b.HasOne("BragadoTripConnect.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BragadoTripConnect.Api.Data.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleRouteOrigin", "ScheduleRouteDestination", "ScheduleDate", "ScheduleTime", "ScheduleCompanyCuit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BragadoTripConnect.Api.Data.Schedule", b =>
                {
                    b.HasOne("BragadoTripConnect.Api.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyCuit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BragadoTripConnect.Api.Data.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteOrigin", "RouteDestination")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
